#ifndef _NFCCXPRICHECKS_H_
#define _NFCCXPRICHECKS_H_

// Compile time asserts (failure results in error C2118: negative subscript)
#ifndef C_ASSERT
#define C_ASSERT(e) typedef char __C_ASSERT__[(e)?1:-1]
#endif // C_ASSERT

//
// Add #define NFCCXPRI_NO_ENUM_CHECKS_Vstubs_NfcCx_version_data_xml if don't want the enum checks to be evaluated
//
// Add #define NFCCXPRI_NO_STRUCT_CHECKS_Vstubs_NfcCx_version_data_xml if don't want the struct checks to be evaluated
//
#ifndef NFCCXPRI_NO_ENUM_CHECKS_Vstubs_NfcCx_version_data_xml

// Checks for enum NFC_CX_DRIVER_FLAGS
C_ASSERT(PREV_VER_SCOPE(NFC_CX_DRIVER_DISABLE_WTD_TIMER) == NEW_VER_SCOPE(NFC_CX_DRIVER_DISABLE_WTD_TIMER));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_DRIVER_DISABLE_NFCEE_DISCOVERY) == NEW_VER_SCOPE(NFC_CX_DRIVER_DISABLE_NFCEE_DISCOVERY));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_DRIVER_DISABLE_RECOVERY_MODE) == NEW_VER_SCOPE(NFC_CX_DRIVER_DISABLE_RECOVERY_MODE));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_DRIVER_DISABLE_HOST_CARD_EMULATION) == NEW_VER_SCOPE(NFC_CX_DRIVER_DISABLE_HOST_CARD_EMULATION));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_DRIVER_HCI_NETWORK_PER_NFCEE) == NEW_VER_SCOPE(NFC_CX_DRIVER_HCI_NETWORK_PER_NFCEE));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_DRIVER_DISABLE_NFCEE_ACTION_NTF) == NEW_VER_SCOPE(NFC_CX_DRIVER_DISABLE_NFCEE_ACTION_NTF));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_DRIVER_ENABLE_EEPROM_WRITE_PROTECTION) == NEW_VER_SCOPE(NFC_CX_DRIVER_ENABLE_EEPROM_WRITE_PROTECTION));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_DRIVER_ISODEP_RNAK_PRESENCE_CHK_SUPPORTED) == NEW_VER_SCOPE(NFC_CX_DRIVER_ISODEP_RNAK_PRESENCE_CHK_SUPPORTED));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_DRIVER_RF_ROUTING_POWER_SUB_STATES_SUPPORTED) == NEW_VER_SCOPE(NFC_CX_DRIVER_RF_ROUTING_POWER_SUB_STATES_SUPPORTED));

// Checks for enum NFC_CX_TRANSPORT_TYPE
C_ASSERT(PREV_VER_SCOPE(NFC_CX_TRANSPORT_I2C) == NEW_VER_SCOPE(NFC_CX_TRANSPORT_I2C));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_TRANSPORT_SPI) == NEW_VER_SCOPE(NFC_CX_TRANSPORT_SPI));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_TRANSPORT_UART) == NEW_VER_SCOPE(NFC_CX_TRANSPORT_UART));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_TRANSPORT_CUSTOM) == NEW_VER_SCOPE(NFC_CX_TRANSPORT_CUSTOM));

// Checks for enum NFC_CX_DEVICE_MODE
C_ASSERT(PREV_VER_SCOPE(NFC_CX_DEVICE_MODE_NCI) == NEW_VER_SCOPE(NFC_CX_DEVICE_MODE_NCI));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_DEVICE_MODE_DTA) == NEW_VER_SCOPE(NFC_CX_DEVICE_MODE_DTA));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_DEVICE_MODE_RAW) == NEW_VER_SCOPE(NFC_CX_DEVICE_MODE_RAW));

// Checks for enum NFC_CX_HOST_ACTION
C_ASSERT(PREV_VER_SCOPE(HostActionStart) == NEW_VER_SCOPE(HostActionStart));
C_ASSERT(PREV_VER_SCOPE(HostActionStop) == NEW_VER_SCOPE(HostActionStop));
C_ASSERT(PREV_VER_SCOPE(HostActionRestart) == NEW_VER_SCOPE(HostActionRestart));
C_ASSERT(PREV_VER_SCOPE(HostActionUnload) == NEW_VER_SCOPE(HostActionUnload));

// Checks for enum NFC_CX_POLL_MODE_CONFIG
C_ASSERT(PREV_VER_SCOPE(NFC_CX_POLL_NFC_A) == NEW_VER_SCOPE(NFC_CX_POLL_NFC_A));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_POLL_NFC_B) == NEW_VER_SCOPE(NFC_CX_POLL_NFC_B));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_POLL_NFC_F_212) == NEW_VER_SCOPE(NFC_CX_POLL_NFC_F_212));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_POLL_NFC_F_424) == NEW_VER_SCOPE(NFC_CX_POLL_NFC_F_424));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_POLL_NFC_15693) == NEW_VER_SCOPE(NFC_CX_POLL_NFC_15693));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_POLL_NFC_ACTIVE) == NEW_VER_SCOPE(NFC_CX_POLL_NFC_ACTIVE));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_POLL_DEFAULT) == NEW_VER_SCOPE(NFC_CX_POLL_DEFAULT));

// Checks for enum NFC_CX_NFCIP_MODE_CONFIG
C_ASSERT(PREV_VER_SCOPE(NFC_CX_NFCIP_NFC_A) == NEW_VER_SCOPE(NFC_CX_NFCIP_NFC_A));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_NFCIP_NFC_F_212) == NEW_VER_SCOPE(NFC_CX_NFCIP_NFC_F_212));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_NFCIP_NFC_F_424) == NEW_VER_SCOPE(NFC_CX_NFCIP_NFC_F_424));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_NFCIP_NFC_ACTIVE) == NEW_VER_SCOPE(NFC_CX_NFCIP_NFC_ACTIVE));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_NFCIP_NFC_ACTIVE_A) == NEW_VER_SCOPE(NFC_CX_NFCIP_NFC_ACTIVE_A));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_NFCIP_NFC_ACTIVE_F_212) == NEW_VER_SCOPE(NFC_CX_NFCIP_NFC_ACTIVE_F_212));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_NFCIP_NFC_ACTIVE_F_424) == NEW_VER_SCOPE(NFC_CX_NFCIP_NFC_ACTIVE_F_424));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_NFCIP_DEFAULT) == NEW_VER_SCOPE(NFC_CX_NFCIP_DEFAULT));

// Checks for enum NFC_CX_NFCIP_TGT_MODE_CONFIG
C_ASSERT(PREV_VER_SCOPE(NFC_CX_NFCIP_TGT_NFC_A) == NEW_VER_SCOPE(NFC_CX_NFCIP_TGT_NFC_A));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_NFCIP_TGT_NFC_F) == NEW_VER_SCOPE(NFC_CX_NFCIP_TGT_NFC_F));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_NFCIP_TGT_NFC_ACTIVE_A) == NEW_VER_SCOPE(NFC_CX_NFCIP_TGT_NFC_ACTIVE_A));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_NFCIP_TGT_NFC_ACTIVE_F) == NEW_VER_SCOPE(NFC_CX_NFCIP_TGT_NFC_ACTIVE_F));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_NFCIP_TGT_DEFAULT) == NEW_VER_SCOPE(NFC_CX_NFCIP_TGT_DEFAULT));

// Checks for enum NFC_CX_CE_MODE_CONFIG
C_ASSERT(PREV_VER_SCOPE(NFC_CX_CE_NFC_A) == NEW_VER_SCOPE(NFC_CX_CE_NFC_A));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_CE_NFC_B) == NEW_VER_SCOPE(NFC_CX_CE_NFC_B));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_CE_NFC_F) == NEW_VER_SCOPE(NFC_CX_CE_NFC_F));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_CE_DEFAULT) == NEW_VER_SCOPE(NFC_CX_CE_DEFAULT));

// Checks for enum NFC_CX_POLL_BAILOUT_CONFIG
C_ASSERT(PREV_VER_SCOPE(NFC_CX_POLL_BAILOUT_DEFAULT) == NEW_VER_SCOPE(NFC_CX_POLL_BAILOUT_DEFAULT));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_POLL_BAILOUT_NFC_A) == NEW_VER_SCOPE(NFC_CX_POLL_BAILOUT_NFC_A));
C_ASSERT(PREV_VER_SCOPE(NFC_CX_POLL_BAILOUT_NFC_B) == NEW_VER_SCOPE(NFC_CX_POLL_BAILOUT_NFC_B));

// Checks for enum NFC_CX_SEQUENCE
C_ASSERT(PREV_VER_SCOPE(SequencePreInit) == NEW_VER_SCOPE(SequencePreInit));
C_ASSERT(PREV_VER_SCOPE(SequenceInitComplete) == NEW_VER_SCOPE(SequenceInitComplete));
C_ASSERT(PREV_VER_SCOPE(SequencePreRfDiscStart) == NEW_VER_SCOPE(SequencePreRfDiscStart));
C_ASSERT(PREV_VER_SCOPE(SequenceRfDiscStartComplete) == NEW_VER_SCOPE(SequenceRfDiscStartComplete));
C_ASSERT(PREV_VER_SCOPE(SequencePreRfDiscStop) == NEW_VER_SCOPE(SequencePreRfDiscStop));
C_ASSERT(PREV_VER_SCOPE(SequenceRfDiscStopComplete) == NEW_VER_SCOPE(SequenceRfDiscStopComplete));
C_ASSERT(PREV_VER_SCOPE(SequencePreNfceeDisc) == NEW_VER_SCOPE(SequencePreNfceeDisc));
C_ASSERT(PREV_VER_SCOPE(SequenceNfceeDiscComplete) == NEW_VER_SCOPE(SequenceNfceeDiscComplete));
C_ASSERT(PREV_VER_SCOPE(SequencePreShutdown) == NEW_VER_SCOPE(SequencePreShutdown));
C_ASSERT(PREV_VER_SCOPE(SequenceShutdownComplete) == NEW_VER_SCOPE(SequenceShutdownComplete));
C_ASSERT(PREV_VER_SCOPE(SequencePreRecovery) == NEW_VER_SCOPE(SequencePreRecovery));
C_ASSERT(PREV_VER_SCOPE(SequenceRecoveryComplete) == NEW_VER_SCOPE(SequenceRecoveryComplete));
C_ASSERT(PREV_VER_SCOPE(SequenceMaximum) == NEW_VER_SCOPE(SequenceMaximum));

#endif // NFCCXPRI_NO_ENUM_CHECKS_Vstubs_NfcCx_version_data_xml

#ifndef NFCCXPRI_NO_STRUCT_CHECKS_Vstubs_NfcCx_version_data_xml

// Checks for struct NFCCX_DRIVER_GLOBALS
C_ASSERT(sizeof(PREV_VER_SCOPE(NFCCX_DRIVER_GLOBALS)) <= sizeof(NEW_VER_SCOPE(NFCCX_DRIVER_GLOBALS)));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFCCX_DRIVER_GLOBALS), Reserved) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFCCX_DRIVER_GLOBALS), Reserved));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFCCX_DRIVER_GLOBALS), Reserved) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFCCX_DRIVER_GLOBALS), Reserved));

// Checks for struct NFC_CX_CLIENT_CONFIG
C_ASSERT(sizeof(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG)) <= sizeof(NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG)));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), Size) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), Size));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), Size) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), Size));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), IsPowerPolicyOwner) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), IsPowerPolicyOwner));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), IsPowerPolicyOwner) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), IsPowerPolicyOwner));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), PowerIdleTimeout) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), PowerIdleTimeout));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), PowerIdleTimeout) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), PowerIdleTimeout));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), PowerIdleType) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), PowerIdleType));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), PowerIdleType) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), PowerIdleType));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), BusType) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), BusType));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), BusType) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), BusType));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), DriverFlags) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), DriverFlags));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), DriverFlags) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), DriverFlags));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), DeviceMode) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), DeviceMode));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), DeviceMode) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), DeviceMode));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), EvtNfcCxWriteNciPacket) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), EvtNfcCxWriteNciPacket));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), EvtNfcCxWriteNciPacket) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), EvtNfcCxWriteNciPacket));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), EvtNfcCxDeviceIoControl) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), EvtNfcCxDeviceIoControl));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_CLIENT_CONFIG), EvtNfcCxDeviceIoControl) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_CLIENT_CONFIG), EvtNfcCxDeviceIoControl));

// Checks for struct NFC_CX_HARDWARE_EVENT
C_ASSERT(sizeof(PREV_VER_SCOPE(NFC_CX_HARDWARE_EVENT)) <= sizeof(NEW_VER_SCOPE(NFC_CX_HARDWARE_EVENT)));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_HARDWARE_EVENT), HardwareStatus) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_HARDWARE_EVENT), HardwareStatus));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_HARDWARE_EVENT), HardwareStatus) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_HARDWARE_EVENT), HardwareStatus));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_HARDWARE_EVENT), HostAction) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_HARDWARE_EVENT), HostAction));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_HARDWARE_EVENT), HostAction) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_HARDWARE_EVENT), HostAction));

// Checks for struct NFC_CX_RF_DISCOVERY_CONFIG
C_ASSERT(sizeof(PREV_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG)) <= sizeof(NEW_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG)));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), Size) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), Size));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), Size) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), Size));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), TotalDuration) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), TotalDuration));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), TotalDuration) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), TotalDuration));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), PollConfig) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), PollConfig));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), PollConfig) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), PollConfig));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), NfcIPMode) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), NfcIPMode));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), NfcIPMode) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), NfcIPMode));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), NfcIPTgtMode) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), NfcIPTgtMode));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), NfcIPTgtMode) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), NfcIPTgtMode));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), NfcCEMode) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), NfcCEMode));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), NfcCEMode) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), NfcCEMode));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), BailoutConfig) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), BailoutConfig));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), BailoutConfig) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_RF_DISCOVERY_CONFIG), BailoutConfig));

// Checks for struct NFC_CX_LLCP_CONFIG
C_ASSERT(sizeof(PREV_VER_SCOPE(NFC_CX_LLCP_CONFIG)) <= sizeof(NEW_VER_SCOPE(NFC_CX_LLCP_CONFIG)));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_LLCP_CONFIG), Size) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_LLCP_CONFIG), Size));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_LLCP_CONFIG), Size) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_LLCP_CONFIG), Size));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_LLCP_CONFIG), Miu) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_LLCP_CONFIG), Miu));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_LLCP_CONFIG), Miu) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_LLCP_CONFIG), Miu));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_LLCP_CONFIG), LinkTimeout) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_LLCP_CONFIG), LinkTimeout));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_LLCP_CONFIG), LinkTimeout) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_LLCP_CONFIG), LinkTimeout));
C_ASSERT(FIELD_OFFSET(PREV_VER_SCOPE(NFC_CX_LLCP_CONFIG), RecvWindowSize) == 
         FIELD_OFFSET( NEW_VER_SCOPE(NFC_CX_LLCP_CONFIG), RecvWindowSize));
C_ASSERT(RTL_FIELD_SIZE(PREV_VER_SCOPE(NFC_CX_LLCP_CONFIG), RecvWindowSize) == 
         RTL_FIELD_SIZE( NEW_VER_SCOPE(NFC_CX_LLCP_CONFIG), RecvWindowSize));

#endif // NFCCXPRI_NO_STRUCT_CHECKS_Vstubs_NfcCx_version_data_xml

#endif // _NFCCXPRICHECKS_H_
